name: Simple Greeting

on: [push]
workflow_dispatch:
  branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Display Message
        run: echo "Hello, GitHub Actions is running successfully!"
      
      - name: Check Branch
        run: |
          echo "This job runs on the ${{ github.ref_name }} branch."
